info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

spring:
    profiles:
        active: local
    application:
        name: herkimer
    datasource:
        url: jdbc:postgresql://localhost:${DATABASE_PORT:5432}/herkimer
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver

logging:
    level:
        no.skatteetaten.aurora.herkimer: DEBUG
        org:
            hibernate: WARN
            springframework: WARN
            apache:
                catalina: WARN
                velocity: WARN
aurora:
    authentication:
        enabled: true
        token:
            header-value-prefix: bearer

---
spring:
    profiles: local

aurora:
    authentication:
        enabled: false
        token:
            value: token

logging:
    pattern:
        console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"

---
spring:
    profiles: openshift

aurora:
    authentication:
        token:
            location: /u01/secrets/app/aurora-token/token
