POST http://localhost:8080/applicationDeployment
Content-Type: application/json

{
  "name": "kris3",
  "environmentName": "dev",
  "cluster": "utv",
  "businessGroup": "aurora"
}

###
GET http://localhost:8080/applicationDeployment
