POST http://localhost:8080/applicationDeployment
Content-Type: application/json

{
  "name": "testApp",
  "environmentName": "dev",
  "cluster": "utv",
  "businessGroup": "aurora",
  "applicationName": "nameForApp"
}

###
GET http://localhost:8080/applicationDeployment
