POST http://localhost:8080/resource
Content-Type: application/json

{
"name": "myDB",
  "kind": "ExternalSchema",
  "ownerId": "af4faf2d6f"
}

###
GET http://localhost:8080/resource?claimedBy=af4faf2d6f&active=true

###
GET http://localhost:8080/resource?claimedBy=61b0b28956&name=objectPrefixAurora-1

###
DELETE http://localhost:8080/resource/89

###
PATCH http://localhost:8080/resource/89
Content-Type: application/json

{
"active": true
}
